### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Jacobs147** [IT-Students-Web-Project/AutoBackup#1]
- [x] Finish my changes
- [x] Push my commits to GitHub
- [x] Open a pull request
